# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisEC
                                 A QGIS plugin
 GIS engeneering communication
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-30
        copyright            : (C) 2022 by Competentit
        email                : info@competentit.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GisEC class from file GisEC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GisEC_extenstion import GisEC_extenstion
    return GisEC_extenstion(iface)
